# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/umartinez/CLionProjects/shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/umartinez/CLionProjects/shell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/umartinez/CLionProjects/shell/CMakeFiles /mnt/c/Users/umartinez/CLionProjects/shell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/umartinez/CLionProjects/shell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Utils

# Build rule for target.
Utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Utils
.PHONY : Utils

# fast build rule for target.
Utils/fast:
	$(MAKE) -f CMakeFiles/Utils.dir/build.make CMakeFiles/Utils.dir/build
.PHONY : Utils/fast

#=============================================================================
# Target rules for targets named ush

# Build rule for target.
ush: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ush
.PHONY : ush

# fast build rule for target.
ush/fast:
	$(MAKE) -f CMakeFiles/ush.dir/build.make CMakeFiles/ush.dir/build
.PHONY : ush/fast

#=============================================================================
# Target rules for targets named Tokenizer

# Build rule for target.
Tokenizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tokenizer
.PHONY : Tokenizer

# fast build rule for target.
Tokenizer/fast:
	$(MAKE) -f CMakeFiles/Tokenizer.dir/build.make CMakeFiles/Tokenizer.dir/build
.PHONY : Tokenizer/fast

mytoc.o: mytoc.c.o

.PHONY : mytoc.o

# target to build an object file
mytoc.c.o:
	$(MAKE) -f CMakeFiles/Tokenizer.dir/build.make CMakeFiles/Tokenizer.dir/mytoc.c.o
.PHONY : mytoc.c.o

mytoc.i: mytoc.c.i

.PHONY : mytoc.i

# target to preprocess a source file
mytoc.c.i:
	$(MAKE) -f CMakeFiles/Tokenizer.dir/build.make CMakeFiles/Tokenizer.dir/mytoc.c.i
.PHONY : mytoc.c.i

mytoc.s: mytoc.c.s

.PHONY : mytoc.s

# target to generate assembly for a file
mytoc.c.s:
	$(MAKE) -f CMakeFiles/Tokenizer.dir/build.make CMakeFiles/Tokenizer.dir/mytoc.c.s
.PHONY : mytoc.c.s

shell.o: shell.c.o

.PHONY : shell.o

# target to build an object file
shell.c.o:
	$(MAKE) -f CMakeFiles/ush.dir/build.make CMakeFiles/ush.dir/shell.c.o
.PHONY : shell.c.o

shell.i: shell.c.i

.PHONY : shell.i

# target to preprocess a source file
shell.c.i:
	$(MAKE) -f CMakeFiles/ush.dir/build.make CMakeFiles/ush.dir/shell.c.i
.PHONY : shell.c.i

shell.s: shell.c.s

.PHONY : shell.s

# target to generate assembly for a file
shell.c.s:
	$(MAKE) -f CMakeFiles/ush.dir/build.make CMakeFiles/ush.dir/shell.c.s
.PHONY : shell.c.s

util.o: util.c.o

.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/Utils.dir/build.make CMakeFiles/Utils.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i

.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/Utils.dir/build.make CMakeFiles/Utils.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s

.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/Utils.dir/build.make CMakeFiles/Utils.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Utils"
	@echo "... ush"
	@echo "... Tokenizer"
	@echo "... mytoc.o"
	@echo "... mytoc.i"
	@echo "... mytoc.s"
	@echo "... shell.o"
	@echo "... shell.i"
	@echo "... shell.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

